### ISSUE TITLE
Grass and Stone Still Drops Diamonds

### ISSUE THREAD

**Issue by Ima-Chris** [BlueDolphinCow/Tropique-Block-Drops-Plugin#1]
Remove the event from the settings, save and restart my server, my configuration only has the default comments but even the grass and stone keep drops diamonds, what else do I do? 

Paper-275 (MC 1.16.4), Plugin is compatible?

**Comment by BlueDolphinCow** [comment]
The issue has already been fixed, turns out I uploaded the wrong file to the releases page. Sorry! I've updated the releases page with the correct file.
